version: '3'
services:
    web:
        image: nginx:alpine
        volumes:
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./:/var/www/html"
            - "./docker/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "${DOCKER_PORT}:80"
        environment:
            - NGINX_HOST=${NGINX_HOST}
            - VIRTUAL_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - mysqldb
    php:
        image: nanoninja/php-fpm:${PHP_VERSION}
        restart: always
        volumes:
            - "./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./:/var/www/html"
    composer:
        image: "composer"
        volumes:
            - "./:/app"
        command: install
    mysqldb:
        image: mysql:${MYSQL_VERSION}
        container_name: ${DB_HOST}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - "8989:3306"
        volumes:
            - "./.data/db/mysql:/var/lib/mysql"
