<?php

include TEMPLATEPATH . '/inc/helpers.php';

if ( ! function_exists( 'iis_start_setup' ) ) {

	/**
	 * IIS Start theme setup
	 * Hooked into the after_setup_theme hook
	 */
	function iis_start_setup() {
		load_theme_textdomain( 'iis-start', get_template_directory() . '/resources/languages' );

		add_theme_support( 'automatic-feed-links' );
		add_theme_support( 'title-tag' );
		add_theme_support( 'post-thumbnails' );
	}

}

add_action( 'after_setup_theme', 'iis_start_setup' );

/**
 * Register and enqueue scripts and styles based on the mix-manifest
 * generated by webpack
 */
function iis_start_assets() {
	// TODO: Cache this
	$mixManifest = get_template_directory() . '/mix-manifest.json';

	if ( file_exists( $mixManifest ) ) {
		$assets = json_decode( file_get_contents( $mixManifest ), TRUE );

		if ( is_array( $assets ) ) {
			foreach ( $assets as $base => $versioned ) {
				list( $name, $type ) = explode( '.', array_pop( explode( '/', $base ) ) );
				$version = array_pop( explode( '?id=', $versioned ) );

				if ( $type == 'css' ) {
					wp_enqueue_style( 'iis-start-style-' . $name, get_stylesheet_directory_uri() . $base, [], $version );
				} else {
					wp_enqueue_script( 'iis-start-script-' . $name, get_stylesheet_directory_uri() . $base, [], $version, true );
				}
			}
		}
	}
}

add_action( 'wp_enqueue_scripts', 'iis_start_assets' );

/**
 * Add external fonts to the head
 */
function iis_start_fonts() {
	echo '<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,800,800i" rel="stylesheet">';
}

add_action( 'wp_head', 'iis_start_fonts' );

/**
 * For security reasons, remove the wordpress generator meta tag
 */
 function remove_generator_filter() {
	 return '';
 }

 $types = array('html', 'xhtml', 'atom', 'rss2', 'comment', 'export');

 foreach ($types as $type) {
	 add_filter( 'get_the_generator_' . $type, 'remove_generator_filter' );
 }
