<?php

if ( ! function_exists( 'iis_start_setup' ) ) {
	/**
	 * IIS Start theme setup
	 * Hooked into the after_setup_theme hook
	 */
	function iis_start_setup() {
		load_theme_textdomain( 'iis-start', get_template_directory() . '/resources/languages' );

		add_theme_support( 'automatic-feed-links' );
		add_theme_support( 'title-tag' );
		add_theme_support( 'post-thumbnails' );
	}
}

add_action( 'after_setup_theme', 'iis_start_setup' );

/**
 * Register and enqueue scripts and styles based on the mix-manifest
 * generated by webpack
 */
function iis_start_assets() {
	wp_enqueue_style( 'iis-start-style', get_stylesheet_directory_uri() . iis_mix('css/site.css'), [], false );
	wp_enqueue_script( 'iis-start-script', get_stylesheet_directory_uri() . iis_mix('js/site.js'), [], false, true );
}

add_action( 'wp_enqueue_scripts', 'iis_start_assets' );

/**
 * For security reasons, remove the WordPress generator meta tag
 */
function remove_generator_filter() {
	return '';
}

$types = [ 'html', 'xhtml', 'atom', 'rss2', 'comment', 'export' ];

foreach ( $types as $generator_type ) {
	add_filter( 'get_the_generator_' . $generator_type, 'remove_generator_filter' );
}
